# Docker Compose Stack for my Home-Server, Knuspii
# Backups are automatically done with a bash script
# Cleanups are automatically done with a bash script
# Disks health is checked with a bash script
# Containers health is checked with a bash script

x-defaults: &defaults
  restart: unless-stopped
  tmpfs:
    - /tmp
  logging:
    driver: json-file
    options:
      max-size: "5m"
      max-file: "1"

services:
  # --- Homepage (Dashboard) ---
  glance:
    container_name: glance
    image: glanceapp/glance:latest
    <<: *defaults
    ports:
      - "80:8080"
    volumes:
      - ./glance:/app/config
    environment:
      - TZ=${TZ}

  # --- AdGuard Home (DNS & Adblock) ---
  adguard:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    <<: *defaults
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
      - "5000:80/tcp"
    environment:
      - TZ=${TZ}
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf


  # --- Filebrowser (Files) ---
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    <<: *defaults
    ports:
      - "5001:8080"
    environment :
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data:/srv
      - ./filebrowser/filebrowser.db:/filebrowser.db
      - ./filebrowser/settings.json:/config/settings.json
    healthcheck:
      disable: true


  # --- Wallos (Finanzen) ---
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    <<: *defaults
    ports:
      - "5002:80"
    environment:
      - TZ=${TZ}
    volumes:
      - ./wallos:/var/www/html/db
      - ./wallos/logos:/var/www/html/images/uploads/logos


  # --- Vikunja (Tasks) ---
  vikunja:
    container_name: vikunja
    image: docker.io/vikunja/vikunja:latest
    user: "1000:1000"
    <<: *defaults
    depends_on:
      mailrise:
        condition: service_started
    ports:
      - "5003:3456"
    environment:
      - TZ=${TZ}
      - VIKUNJA_SERVICE_SECRET=${VIKUNJA_SECRET}
      - VIKUNJA_SERVICE_PUBLICURL=http://home-server:5003
      - VIKUNJA_SERVICE_ENABLEREGISTRATION=false
      #- VIKUNJA_WEBHOOKS_ENABLED=true
      #- VIKUNJA_OUTGOINGREQUESTS_ALLOWNONROUTABLEIPS=true
      - VIKUNJA_MAILER_ENABLED=true
      - VIKUNJA_MAILER_HOST=mailrise
      - VIKUNJA_MAILER_FORCESSL=false
      - VIKUNJA_MAILER_PORT=8025
      - VIKUNJA_MAILER_USERNAME=todo@knuspii.net
      - VIKUNJA_DATABASE_TYPE=sqlite
      - VIKUNJA_DATABASE_PATH=/app/vikunja/files/vikunja.db
    volumes:
      - ./vikunja:/app/vikunja/files:Z
  # --- Mailrise (SMTP relay) ---
  mailrise:
    container_name: mailrise
    image: docker.io/yoryan/mailrise:latest
    <<: *defaults
    dns:
      - 1.1.1.1
    ports:
      - "8025:8025"
    volumes:
      - ./mailrise/mailrise.conf:/etc/mailrise.conf:ro,Z


  # --- Glances (Monitoring) ---
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    <<: *defaults
    ports:
      - "5004:61208"
    environment:
      - TZ=${TZ}
      - GLANCES_OPT=-w -B 0.0.0.0 --config /etc/glances/glances.conf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./glances/glances.conf:/etc/glances/glances.conf:ro
    pid: host
    read_only: true


  # --- n8n (Workflow Automation) ---
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    <<: *defaults
    ports:
      - "5005:5678"
    environment:
      - TZ=${TZ}
      - GENERIC_TIMEZONE=${TZ}
      - N8N_HOST=n8n.home-server
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=child_process
    volumes:
      - ./n8n:/home/node/.n8n


# --- Aria2 (Download Manager) ---
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    <<: *defaults
    ports:
      - "6800:6800"
    environment:
      - TZ=${TZ}
      - RPC_SECRET=${ARIA2_SECRET}
      - RPC_PORT=6800
      - PUID=1000
      - PGID=1000
    volumes:
      - ./aria2/config:/config
      - /mnt/data/Downloads:/downloads
  # --- AriaNg (WebUI) ---
  ariang:
    container_name: ariang
    image: p3terx/ariang
    <<: *defaults
    ports:
      - "5006:6880"


  minecraft-srv:
    container_name: minecraft-srv
    image: itzg/minecraft-server:latest
    <<: *defaults
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - TYPE=FABRIC
      - VERSION=1.20.1
      - MEMORY=4G
      - TZ=${TZ}
      # Old Docker-Sleeper (for < 1.21.2)
      - ENABLE_AUTOPAUSE=true
      - AUTOPAUSE_TIMEOUT_EST=1800
    volumes:
      - ./minecraft-srv:/data
    mem_limit: "4500m"
    cpus: "2.0"

networks:
  default:
    name: homeserver_network
    driver: bridge
